### ISSUE TITLE
Performance issues 

### ISSUE THREAD

**Issue by elfrenqv** [metal3d/docker-ng#1]
I have been trying to use docker to use Angular cli, but I see some performance issues, a simple app saying **App works!** takes 6805ms to build instead the 683ms without docker. I have being reading about this but can't find any solution, do you have any idea?

**Comment by metal3d** [comment]
Strange, I don't have that kind of issue. Can you tell me how you ran the container ?

**Comment by elfrenqv** [comment]
Seems like the issue is only in Mac, this is a docker issue and not yours, here is the link to the forum discussion https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/181

Closing the issue
